apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-test-pv
  labels:
    type: local
spec:
  storageClassName: db-test-path
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: db-test-pvc
  hostPath:
    path: "/mnt/data"