apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: prod-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - brianbrown.dev
    - www.brianbrown.dev
    secretName: prod-tls
  rules:
  - host: brianbrown.dev
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: prod-api
            port:
              number: 80
      - path: /me
        pathType: Prefix
        backend:
          service:
            name: prod-me
            port:
              number: 80
      - path: /budget
        pathType: Prefix
        backend:
          service:
            name: prod-budget
            port:
              number: 80
      - path: /groceries
        pathType: Prefix
        backend:
          service:
            name: prod-groceries
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-portfolio
            port:
              number: 80


