apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-budget
  labels:
    app: test-budget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-budget
  template:
    metadata:
      labels:
        app: test-budget
    spec:
      containers:
      - name: webserver
        image: ghcr.io/brianbrowndev/b-budget:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: test-budget
spec:
  selector:
    app: test-budget
  ports:
    - protocol: TCP
      port: 4100
      targetPort: 80
      name: http
  clusterIP: None
  type: ClusterIP