apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-me
  labels:
    app: prod-me
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: prod-me
  template:
    metadata:
      labels:
        app: prod-me
    spec:
      containers:
      - name: webserver
        image: ghcr.io/b-twice/b-me:v3.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: prod-me
spec:
  selector:
    app: prod-me
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
      name: http
  clusterIP: None
  type: ClusterIP