apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-portfolio
  labels:
    app: test-portfolio
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test-portfolio
  template:
    metadata:
      labels:
        app: test-portfolio
    spec:
      containers:
      - name: webserver
        image: ghcr.io/b-twice/b-site:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: test-portfolio
spec:
  selector:
    app: test-portfolio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  clusterIP: None
  type: ClusterIP
