apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-portfolio
  labels:
    app: prod-portfolio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prod-portfolio
  template:
    metadata:
      labels:
        app: prod-portfolio
    spec:
      containers:
      - name: webserver
        image: ghcr.io/b-twice/b-site:v4.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: prod-portfolio
spec:
  selector:
    app: prod-portfolio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  clusterIP: None
  type: ClusterIP
