name: Publish Webhook Image
on:
  push:
    paths:
      - "webhook/Dockerfile"

jobs:
  deploy:
    name: "Webhook - Build And Push docker images"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Webhook
        id: docker_build_webhook
        uses: docker/build-push-action@v2
        with:
          context: webhook
          file: webhook/Dockerfile
          push: true
          tags: ghcr.io/brianbrowndev/webhook:latest
      - name: webhook Image digest
        run: echo webhook ${{ steps.docker_build_webhook.outputs.digest }}
